language: node_js
node_js:
  - 'stable'
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: jkjones.dev@gmail.com
  api_key:
    secure: B6KliSsICXB1DoU6fO9ijj2b88JjjO6qXP1J0Xal6za55rNXlKCuKuel9fPKZXdMASBTClO7xGSk9zXmvnOJGq5euqTr9Nn80KEzvXA0VdS/wxbATO0qj+a5YRNGVX1v6MHByY2YPpKdE0sGCiTgIpvFTnpWYwemfCNE/BWqE0oWu/a0oJYzryWCaUCIktVxbiL46h25snhPdyknqLQQJ3CD98y9JKRKdgUOxTQ1+fptqMh0xKUEkONGZu4+117KfPNVrw57O/XOSWMkUT6SCN0rDxmkDLh3lXjTtQf2DzAikoLQN7OTqHzJsZ7yTpifPISyE17gAdPYn0IRXOVWIbALVxeqwUCR3xe9n7JPbjdSX9K2UlDrT6yosbHiLGzKegd8CbedgHJMXmiv+zCkb15ewmt3PPZ295HEf8bj/Gq9EJeCLcawuopJgRbH4PjtvMtAeEuQ2Or6sYboyWjDLMtQRIcKG0MAhvalYefGk7otlsXiI8LbQO/nyk+MkhGLRUK7r+lHa/rTkI/wHyuhg8h5mVryCEE78rhwpCWfwTQ/fzgs0swY3V07ABH2F9Bgdvqt1+T22oUYE4+Pnx5YN+5RtXJ89O7YsZK3k95FikKyhEQuHx1NcTeyeYeLUqeFnoX5ktFk7AkFBQPZeeu3VmYCStreEA+5659WYnomTN0=
  on:
    tags: true
    repo: Jaredk3nt/enums
